/**
 * Created with IntelliJ IDEA.
 * User: Bob_Mk2
 * Date: 13/03/30
 * Time: 1:43
 * To change this template use File | Settings | File Templates.
 */

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class EvenFibonacciNumbers {

	/**
	 * フィボナッチ数列において項の値が最大値(max)以下の偶数の値の和を返す
	 * @param max 最大
	 * @return 偶数の項の値の和
	 */
	public int compute(int max) {
		int sum = 0;
		int lastValue = 0;
		int value = 1;
		int tmp = 0;

		//現在の項が最大値を上回ったらループを終了する
		while (value <= max) {
			if (value % 2 == 0) {
				//今の項の値が偶数なので合計値に加える
				sum += value;
			}

			//一つ前の項の値をtmpに逃がしておく
			tmp = lastValue;

			//一つ前の項と現在の項の値を更新する
			lastValue = value;
			value += tmp;
		}

		return sum;
	}

	public static void main(String[] args) {
		EvenFibonacciNumbers e = new EvenFibonacciNumbers();
		System.out.println("Answer is " + e.compute(4000000));
	}
}
